[build]
  command = "pnpm run build"
  ## publish directory is automatically detected by Next.js Runtime
  
  environment = { NPM_FLAGS = "--no-audit" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
