[build]
  command = "pnpm run build"
  publish = ".next"

[context.production]
  command = "pnpm run build"

[context.deploy-preview]
  command = "pnpm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"
