services:
  - type: web
    name: majorly-backend
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: Dockerfile
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: APP_NAME
        value: Majorly
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
    region: ohio
