name: Seed Database

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, zip
          tools: composer:v2

      - name: Install Dependencies
        working-directory: ./backend
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Migrations
        working-directory: ./backend
        run: php artisan migrate:fresh --force
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Download O*NET Data
        working-directory: ./backend
        run: php artisan majorly:download-open-data

      - name: Import O*NET Data
        working-directory: ./backend
        run: php artisan majorly:import-open-data
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
